import Foundation

/// Build token for development mode device registration
///
/// ⚠️ THIS FILE IS AUTO-GENERATED DURING RELEASES
/// ⚠️ DO NOT MANUALLY EDIT THIS FILE
///
/// Generated: 2025-10-26 00:16:45 UTC
/// Release: Auto-generated by scripts/release_ios_sdk.sh
///
/// Security Model:
/// - This file is in .gitignore (not committed to main branch)
/// - Real tokens are ONLY in release tags (for SPM distribution)
/// - Token is used ONLY when SDK is in .development mode
/// - Backend validates token via POST /api/v1/devices/register/dev
///
/// Token Properties:
/// - Format: bt_<uuid>_<timestamp>
/// - Rotatable: Each release gets a new token
/// - Revocable: Backend can mark token as inactive
/// - Rate-limited: Backend enforces 100 req/min per device
enum BuildToken {
    /// Development mode build token
    /// Generated at: 2025-10-26 00:16:45 UTC
    static let token = "bt_611554fd-d99e-46bf-8f84-205164c77a4f_1761437796"
}
